name: Peter Neugebauer's website
description: >
    Peter Neugebauer's website
about: >
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.

master_repo: false
url: https://peterneugebauer.com
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-seo-tag']

logo:

owner:
  name: Peter Neugebauer
  email: #"emai@ddd.de"
  # Social networking links used in footer. Update and remove as you like.
  twitter: #tweetr
  github: 
  stackexchange:
  linkedin: 
  # For Google Authorship https://plus.google.com/authorship

# Analytics and webmaster tools stuff goes here
google_analytics: #footer
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
